// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nfsgaeqyribbqfczbrpt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5mc2dhZXF5cmliYnFmY3picnB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MjA1NTcsImV4cCI6MjA2MjI5NjU1N30.rJZHu3Mi_pFaxYK90EeqQIQTFURH4bsOB1J0Ylg8ZhE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
